/**
 * Applies pending Drizzle migrations (imright/scripts/db/migrations/*.sql,
 * generated by `drizzle-kit generate` — never hand-edited). Safe to call on
 * every process boot: already-applied migrations are skipped (Drizzle tracks
 * this in its own internal table), and the whole run is wrapped in a
 * Postgres advisory lock so two Railway instances booting concurrently
 * during a deploy can't double-apply.
 *
 * Also runnable standalone via `npm run migrate`.
 */

import { fileURLToPath } from 'url';
import path from 'path';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { getPool } from '../db.js';
import { getDb } from './index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_FOLDER = path.join(__dirname, 'migrations');

// Arbitrary but fixed 64-bit key, namespacing this lock from any other
// advisory lock this app might ever take.
const MIGRATION_LOCK_KEY = 'imright_migrations';

export async function runMigrations() {
  const pool = getPool();
  const db = getDb();
  if (!pool || !db) {
    console.warn('[migrate] DATABASE_URL not set; skipping migrations.');
    return;
  }

  // Advisory locks are session-scoped, so the lock/unlock pair must share one
  // checked-out client, not the pool (which could hand out a different
  // connection per query).
  const client = await pool.connect();
  // See wiki_searcher/embeddingIndex.js's identical listener for why this is
  // needed: pg-pool removes its own error listener the moment a client is
  // checked out, so an unexpected connection drop here would otherwise crash
  // the process via an unhandled 'error' event instead of surfacing as a
  // normal query rejection.
  client.on('error', (err) => {
    console.error('[migrate] DB connection error:', err.message);
  });
  try {
    await client.query('SELECT pg_advisory_lock(hashtext($1))', [MIGRATION_LOCK_KEY]);
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
    console.log('[migrate] Migrations up to date.');
  } finally {
    await client.query('SELECT pg_advisory_unlock(hashtext($1))', [MIGRATION_LOCK_KEY]);
    client.release();
  }
}

// `node imright/scripts/db/migrate.js` runs this standalone (npm run migrate).
if (import.meta.url === `file://${process.argv[1]}`) {
  const { loadEnv } = await import('../../load-env.js');
  loadEnv();
  await runMigrations();
  process.exit(0);
}
